//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAS_WPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodItem
    {
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public Nullable<bool> Tomatoes { get; set; }
        public Nullable<bool> Eggs { get; set; }
        public Nullable<bool> Carrots { get; set; }
        public Nullable<bool> Note { get; set; }
    }
}
