//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAS_WPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public System.Guid ID { get; set; }
        public System.Guid UserID { get; set; }
        public System.DateTime Time { get; set; }
        public bool FullDay { get; set; }
        public bool WarmMeal { get; set; }
        public string Drink1 { get; set; }
        public string Drink2 { get; set; }
    
        public virtual User User { get; set; }
    }
}
